fallback = ' '
separator = '  '

# These are tested in order; the first pattern that matches, wins.
[matching]
# config
'/\.conf$/' = ''
'/\.doc$/' = ''
'/\.exe$/' = ''
'/\.ini$/' = ''
'/\.json$/' = ''
'/\.md$/' = ''
'/\.mdx$/' = ''
'/\.pdf$/' = ''
'/\.ppt$/' = ''
'/\.toml$/' = ''
'/\.xls$/' = ''
'/\.xml$/' = ''
'/\.yam$/' = ''
'/\.yaml$/' = ''

# languages
'/\.ai$/'       = ''
'/\.c$/'        = ''
'/\.c++$/'      = ''
'/\.cc$/'       = ''
'/\.clj$/'      = ''
'/\.cljc$/'     = ''
'/\.cljs$/'     = ''
'/\.coffee$/'   = ''
'/\.cp$/'       = ''
'/\.cpp$/'      = ''
'/\.cs$/'       = ''
'/\.css$/'      = ''
'/\.cxx$/'      = ''
'/\.d$/'        = ''
'/\.dart$/'     = ''
'/\.db$/'       = ''
'/\.diff$/'     = ''
'/\.dump$/'     = ''
'/\.edn$/'      = ''
'/\.eex$/'      = ''
'/\.elm$/'      = ''
'/\.erl$/'      = ''
'/\.ex$/'       = ''
'/\.exs$/'      = ''
'/\.f#$/'       = ''
'/\.fs$/'       = ''
'/\.fsi$/'      = ''
'/\.fsscript$/' = ''
'/\.fsx$/'      = ''
'/\.gemspec$/'  = ''
'/\.go$/'       = ''
'/\.h$/'        = ''
'/\.heex$/'     = ''
'/\.hh$/'       = ''
'/\.hpp$/'      = ''
'/\.hrl$/'      = ''
'/\.hs$/'       = ''
'/\.html$/'     = ''
'/\.hxx$/'      = ''
'/\.java$/'     = ''
'/\.jl$/'       = ''
'/\.js$/'       = ''
'/\.jsx$/'      = ''
'/\.leex$/'     = ''
'/\.less$/'     = ''
'/\.lhs$/'      = ''
'/\.lua$/'      = ''
'/\.mjs$/'      = ''
'/\.ml$/'       = 'λ'
'/\.mli$/'      = 'λ'
'/\.nix$/'      = ''
'/\.pem$'      = ''
'/\.php$/'      = ''
'/\.pl$/'       = ''
'/\.pm$/'       = ''
'/\.pp$/'       = ''
'/\.psb$/'      = ''
'/\.psd$/'      = ''
'/\.py$/'       = ''
'/\.pyc$/'      = ''
'/\.pyd$/'      = ''
'/\.pyo$/'      = ''
'/\.r$/'       = 'ﳒ'
'/\.rake$/'     = ''
'/\.rb$/'       = ''
'/\.rlib$/'     = ''
'/\.rproj$'    = '鉶'
'/\.rs$/'       = ''
'/\.rss$/'      = ''
'/\.sass$/'     = ''
'/\.scala$/'    = ''
'/\.scss$/'     = ''
'/\.sh$/'       = ''
'/\.sln$/'      = ''
'/\.sql$/'      = ''
'/\.suo$/'      = ''
'/\.swift$/'    = ''
'/\.t$/'        = ''
'/\.ts$/'       = ''
'/\.tsx$/'      = ''
'/\.twig$/'     = ''
'/\.vim$/'      = ''
'/\.xcplayground$/'    = ''
'/\.xul$/'      = ''

# image extension
'/\.bmp$/' = ''
'/\.gif$/' = ''
'/\.ico$/' = ''
'/\.jpeg$/' = ''
'/\.jpg$/' = ''
'/\.png$/' = ''
'/\.webp$/' = ''

# Terminals
'/nvim/' = ''

'/nix/' = ''
'/git/' = ''
'/lazygit/' = ''
'/diff/' = ''

# editors
'Code' = ''
'code-oss' = ''
'code-url-handler' = ''

'jetbrains-idea-ce' = 'IJ'
'jetbrains-studio' = 'IJ'

'/npm/' = ''
'/node_modules/' = ''
'/node/' = ''
'/yarn/' = ''

# browsers
# more specific higher order
'/(?i).*Invidious.*Firefox/' = ''
'/(?i)Github.*Firefox/' = ''
'/(?i)Github/' = ''
'/(?i)Gitlab.*Firefox/' = ''
'/(?i)Google Calendar.*Firefox/' = ''
'/(?i)drive.*Firefox/' = ''
'/(?i)h2.*Firefox/' = ''
'/(?i)reddit.*Firefox/' = ''
'/Firefox .*Private Browsing/' = ''
'/(?i)Google-chrome/' = ''
'Nightly' = ''
'Tor Browser' = ''
'brave-browser' = ''
'chromium' = ''
'firefox' = ''
'firefoxdeveloperedition' = ''

# app
'openaws-vpn-client' = ''
'kitty' = ''
'Alacritty' = ''
'Bitwarden' = ''
'FreeFileSync' = ''
'GParted' = ''
'Gimp' = ''
'GitHub Desktop' = ''
'google-chrome' = ''
'Insomnia' = ''
'Pinta' = '🖌'
'/(?i)Signal/' = ''
'Slack' = ''
'Steam' = ''
'Thunderbird' = ''
'anki' = ''
'balena-etcher' = ''
'blueberry.py' = ''
'calculator' = ''
'calibre-gui' = ''
'com.github.tenderowl.frog' = ''
'com.gitlab.zehkira.Myuzi' = ''
'com.nextcloud.desktopclient.nextcloud' = ''
'czkawka-gui' = ''
'discord' = ''
'eog' = ''
'filezilla' = ''
'galculator' = '🖩'
'gimagereader-gtk' = ''
'gimagereader-qt' = ''
'github' = ''
'libreoffice' = ''
'libreoffice-calc' = ''
'libreoffice-writer' = ''
'menu' = ''
'mpd' = ''
'mpv' = ''
'ncmpcpp' = ''
'nemo' = ''
'nuclear' = ''
'obs' = ''
'org.gnome.Nautilus' = ''
'org.kde.ark' = ''
'org.kde.digikam' = '🖌'
'org.ksnip.ksnip' = '🖌'
'org.qbittorrent.qBittorrent' = ''
'org.telegram.desktop' = ''
'pamac-manager' = ''
'pavucontrol' = ''
'telegramdesktop' = ''
'tenacity' = ''
'thunar' = ''
'transmission' = ''
'videostream' = ''
'vimiv' = ''
'virt-manager' = ''
'vlc' = ''
'wdisplays' = '🖵'
